import Head from "next/head";
import { AddTodoForm } from "../components/AddTodoForm";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Task Manager App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <h1 className={styles.title}>My Task Manager</h1>
          <ul className={styles.list}>
            <li className={styles.listItem}>
              <label className={styles.label}>
                <input type="checkbox" />
                <span className={styles.labelText}>Buy oat milk</span>
              </label>
            </li>
          </ul>
          <AddTodoForm />
        </div>
      </main>
    </div>
  );
}
